// Canonical premium programs data used across homepage and premium-programs page
export const premiumPrograms = [
  {
    id: 'bac_2025',
    type: 'bac_2025',
    title: 'Abonament BAC 2025',
    subtitle: 'Pregătire completă pentru Bacalaureat',
    price: 199.99,
    originalPrice: 299.99,
    duration: '12 luni',
    description:
      'Accesul complet la toate resursele necesare pentru a obține o notă excelentă la BAC.',
    features: [
      'Toate fișele de matematică pentru BAC',
      'Simulări complete cu cronometru',
      'Rezolvări pas cu pas pentru toate exercițiile',
      'Teste de evaluare săptămânale',
      'Suport prioritar prin chat',
      'Acces la sesiuni live de pregătire',
      'Certificat de completare',
      'Garanție de îmbunătățire a notei',
    ],
    badge: 'Cel mai popular',
    badgeColor: 'bg-orange-500',
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'evaluare_nationala',
    type: 'evaluare_nationala',
    title: 'Evaluare Națională 2025',
    subtitle: 'Pentru elevii din clasa a VIII-a',
    price: 149.99,
    originalPrice: 199.99,
    duration: '6 luni',
    description:
      'Pregătire specializată pentru evaluarea națională cu exerciții adaptate nivelului.',
    features: [
      'Fișe pentru clasa a VIII-a',
      'Teste de evaluare națională din anii anteriori',
      'Simulări cronometrate',
      'Rezolvări detaliate',
      'Programe de studiu personalizate',
      'Suport pentru părinți',
      'Rapoarte de progres',
      'Acces la comunitatea de elevi',
    ],
    badge: 'Recomandat',
    badgeColor: 'bg-blue-500',
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'premium_cursuri',
    type: 'premium_cursuri',
    title: 'Cursuri Premium',
    subtitle: 'Video cursuri interactive',
    price: 99.99,
    originalPrice: 149.99,
    duration: '6 luni',
    description:
      'Cursuri video premium cu explicații detaliate și exerciții interactive.',
    features: [
      'Peste 100 de ore de video cursuri',
      'Exerciții interactive',
      'Workshopuri exclusive',
      'Materiale descărcabile',
      'Quiz-uri de verificare',
      'Certificat de absolvire',
      'Acces offline prin aplicația mobilă',
      'Actualizări gratuite de conținut',
    ],
    badge: 'Nou',
    badgeColor: 'bg-green-500',
    color: 'from-green-500 to-teal-500',
  },
  {
    id: 'fise_complete',
    type: 'fise_complete',
    title: 'Fișe Complete',
    subtitle: 'Toate fișele într-un singur pachet',
    price: 49.99,
    originalPrice: 79.99,
    duration: '3 luni',
    description:
      'Acces la toate fișele de matematică pentru toate clasele.',
    features: [
      'Toate fișele pentru clasele V-XII',
      'Download nelimitat',
      'Format PDF de înaltă calitate',
      'Actualizări automate',
      'Organizare pe capitole',
      'Sistem de bookmark-uri',
      'Printare nelimitată',
      'Acces pe toate dispozitivele',
    ],
    badge: null,
    badgeColor: null,
    color: 'from-purple-500 to-pink-500',
  },
];

export const homepagePremiumPrograms = premiumPrograms.slice(0, 3);
