-- Migration to add demo users for testing authentication
-- This migration creates demo users in auth.users and corresponding user_profiles

-- Insert demo users into auth.users table
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  email_change,
  email_change_token_new,
  email_change_token_current,
  last_sign_in_at,
  raw_user_meta_data,
  created_at,
  updated_at,
  is_super_admin,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES
(
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid,
  '00000000-0000-0000-0000-000000000000'::uuid,
  'authenticated',
  'authenticated',
  'admin@matecusucces.ro',
  crypt('admin123', gen_salt('bf')),
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NULL,
  '{"role": "admin"}',
  NOW(),
  NOW(),
  false,
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
),
(
  'b1ffcd99-9c1b-4ef8-bb7d-7bb9bd381a22'::uuid,
  '00000000-0000-0000-0000-000000000000'::uuid,
  'authenticated',
  'authenticated',
  'elev@matecusucces.ro',
  crypt('elev123', gen_salt('bf')),
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NULL,
  '{"role": "student"}',
  NOW(),
  NOW(),
  false,
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
),
(
  'c2ffdd99-9c2b-4ef8-bb8d-8bb9bd382a33'::uuid,
  '00000000-0000-0000-0000-000000000000'::uuid,
  'authenticated',
  'authenticated',
  'parinte@matecusucces.ro',
  crypt('parinte123', gen_salt('bf')),
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NULL,
  '{"role": "parent"}',
  NOW(),
  NOW(),
  false,
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
),
(
  'd3ffee99-9c3b-4ef8-bb9d-9bb9bd383a44'::uuid,
  '00000000-0000-0000-0000-000000000000'::uuid,
  'authenticated',
  'authenticated',
  'demo@matecusucces.ro',
  crypt('demo123', gen_salt('bf')),
  NOW(),
  NOW(),
  '',
  NULL,
  '',
  NULL,
  '',
  '',
  '',
  NULL,
  '{"role": "student"}',
  NOW(),
  NOW(),
  false,
  NULL,
  NULL,
  '',
  '',
  NULL,
  0,
  NULL,
  '',
  NULL,
  false,
  NULL
)
ON CONFLICT (id) DO NOTHING;

-- Insert corresponding user profiles
INSERT INTO public.user_profiles (
  id,
  email,
  full_name,
  role,
  grade_level,
  preferences,
  created_at,
  updated_at
) VALUES
(
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid,
  'admin@matecusucces.ro',
  'Administrator Demo',
  'admin'::user_role,
  NULL,
  '{"theme": "default", "language": "ro"}',
  NOW(),
  NOW()
),
(
  'b1ffcd99-9c1b-4ef8-bb7d-7bb9bd381a22'::uuid,
  'elev@matecusucces.ro',
  'Elev Demo',
  'student'::user_role,
  'clasa_10'::grade_level,
  '{"theme": "default", "language": "ro", "subjects": ["matematica", "fizica"]}',
  NOW(),
  NOW()
),
(
  'c2ffdd99-9c2b-4ef8-bb8d-8bb9bd382a33'::uuid,
  'parinte@matecusucces.ro',
  'Părinte Demo',
  'parent'::user_role,
  NULL,
  '{"theme": "default", "language": "ro", "children_grade": "clasa_10"}',
  NOW(),
  NOW()
),
(
  'd3ffee99-9c3b-4ef8-bb9d-9bb9bd383a44'::uuid,
  'demo@matecusucces.ro',
  'Demo User',
  'student'::user_role,
  'clasa_12'::grade_level,
  '{"theme": "default", "language": "ro", "subjects": ["matematica"]}',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;

-- Create some sample subscriptions for demo users
INSERT INTO public.subscriptions (
  id,
  user_id,
  subscription_type,
  status,
  start_date,
  end_date,
  price,
  features,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'b1ffcd99-9c1b-4ef8-bb7d-7bb9bd381a22'::uuid,
  'bac_2025'::subscription_type,
  'active'::subscription_status,
  NOW(),
  NOW() + INTERVAL '1 year',
  199.99,
  '{"access_level": "premium", "worksheets": "unlimited", "practice_tests": true}',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'd3ffee99-9c3b-4ef8-bb9d-9bb9bd383a44'::uuid,
  'premium_cursuri'::subscription_type,
  'active'::subscription_status,
  NOW(),
  NOW() + INTERVAL '6 months',
  99.99,
  '{"access_level": "premium", "courses": "all", "support": true}',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO NOTHING;